"""add_session_table_and_cascade

Revision ID: 53615b25087d
Revises: 719c710fbddf
Create Date: 2025-11-20 14:59:50.361082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53615b25087d"
down_revision: Union[str, Sequence[str], None] = "719c710fbddf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column(
            "session_id",
            sa.Text(),
            nullable=False,
            comment="세션 고유 ID (UUID)",
        ),
        sa.Column(
            "user_id", sa.BIGINT(), nullable=False, comment="세션 소유자"
        ),
        sa.Column("title", sa.Text(), nullable=True, comment="세션 제목"),
        sa.Column(
            "context_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=True,
            comment="세션 컨텍스트 (예: doc_ids_filter)",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False
    )
    op.alter_column(
        "chat_history",
        "session_id",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_comment="채팅 세션 ID. 동일한 대화를 그룹화하는 데 사용됩니다.",
    )
    op.create_foreign_key(
        None,
        "chat_history",
        "sessions",
        ["session_id"],
        ["session_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "session_attachments",
        "session_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="이 파일이 첨부된 세션 ID",
        existing_nullable=False,
    )
    op.alter_column(
        "session_attachments",
        "user_id",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="첨부한 사용자 ID (FK to users.user_id)",
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("session_attachments_user_id_fkey"),
        "session_attachments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "session_attachments",
        "users",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "session_attachments",
        "sessions",
        ["session_id"],
        ["session_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session_attachments",
        sa.Column(
            "pending_review_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="영구 지식으로 승격 요청 시 사용자가 제출한 메타데이터 (대상 KB, 권한 그룹 등)",
        ),
    )
    op.drop_constraint(None, "session_attachments", type_="foreignkey")
    op.create_foreign_key(
        op.f("session_attachments_user_id_fkey"),
        "session_attachments",
        "users",
        ["user_id"],
        ["user_id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "session_attachments",
        "user_id",
        existing_type=sa.BIGINT(),
        comment="첨부한 사용자 ID (FK to users.user_id)",
        existing_nullable=True,
    )
    op.alter_column(
        "session_attachments",
        "session_id",
        existing_type=sa.TEXT(),
        comment="이 파일이 첨부된 세션 ID",
        existing_nullable=False,
    )
    op.drop_constraint(None, "chat_history", type_="foreignkey")
    op.alter_column(
        "chat_history",
        "session_id",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_comment="채팅 세션 ID. 동일한 대화를 그룹화하는 데 사용됩니다.",
    )
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
