"""initial_mvp_schema

Revision ID: 719c710fbddf
Revises: 
Create Date: 2025-11-20 10:52:21.124928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '719c710fbddf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), sa.Identity(always=False), nullable=False, comment='사용자 고유 ID (PK, 자동 증가)'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='사용자 이름 (로그인 시 사용, 고유값)'),
    sa.Column('hashed_password', sa.Text(), nullable=False, comment='해시 처리된 비밀번호'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='계정 생성일 (UTC)'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False, comment='계정 활성화 여부 (비활성화 시 로그인 불가)'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_history',
    sa.Column('message_id', sa.BIGINT(), sa.Identity(always=False), nullable=False, comment='메시지 고유 ID (PK, 자동 증가)'),
    sa.Column('user_id', sa.BIGINT(), nullable=False, comment='메시지를 작성한 사용자 ID (FK to users.user_id)'),
    sa.Column('session_id', sa.Text(), nullable=True, comment='채팅 세션 ID. 동일한 대화를 그룹화하는 데 사용됩니다.'),
    sa.Column('role', sa.String(length=20), nullable=False, comment="메시지 작성자 역할 ('user' 또는 'assistant')"),
    sa.Column('content', sa.Text(), nullable=False, comment='메시지 내용'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='메시지 생성 시간 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('session_attachments',
    sa.Column('attachment_id', sa.BIGINT(), sa.Identity(always=False), nullable=False, comment='첨부파일 고유 ID (PK)'),
    sa.Column('session_id', sa.Text(), nullable=False, comment='이 파일이 첨부된 세션 ID'),
    sa.Column('user_id', sa.BIGINT(), nullable=True, comment='첨부한 사용자 ID (FK to users.user_id)'),
    sa.Column('file_name', sa.Text(), nullable=False, comment='원본 파일 이름'),
    sa.Column('file_path', sa.Text(), nullable=False, comment='저장된 경로 (예: S3 키 또는 로컬 경로)'),
    sa.Column('status', sa.String(length=50), server_default='indexing', nullable=False, comment='파일 상태: indexing, temporary, pending_review, promoted, rejected, failed'),
    sa.Column('pending_review_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='영구 지식으로 승격 요청 시 사용자가 제출한 메타데이터 (대상 KB, 권한 그룹 등)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index(op.f('ix_session_attachments_session_id'), 'session_attachments', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_attachments_user_id'), 'session_attachments', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('user_id', sa.BIGINT(), nullable=False, comment='프로필 소유 사용자의 ID (PK, FK to users.user_id)'),
    sa.Column('profile_text', sa.Text(), nullable=True, comment="사용자 프로필 내용 (예: '나는 파이썬 백엔드 개발자입니다.')"),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='마지막 프로필 업데이트 시간 (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('session_attachment_chunks',
    sa.Column('chunk_id', sa.BIGINT(), sa.Identity(always=False), nullable=False, comment='임시 청크의 고유 ID (PK)'),
    sa.Column('attachment_id', sa.BIGINT(), nullable=False, comment='부모 첨부파일의 ID (FK to session_attachments.attachment_id)'),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='분할된 조각의 텍스트'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False, comment='텍스트에 대한 벡터 임베딩 (pgvector 타입)'),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='청크 관련 추가 메타데이터 (JSONB 형식)'),
    sa.ForeignKeyConstraint(['attachment_id'], ['session_attachments.attachment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_session_attachment_chunks_attachment_id'), 'session_attachment_chunks', ['attachment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_attachment_chunks_attachment_id'), table_name='session_attachment_chunks')
    op.drop_table('session_attachment_chunks')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_session_attachments_user_id'), table_name='session_attachments')
    op.drop_index(op.f('ix_session_attachments_session_id'), table_name='session_attachments')
    op.drop_table('session_attachments')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
