FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y git
RUN pip install torch --index-url https://download.pytorch.org/whl/cpu
COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt
COPY . .